site_name: 'enphase'
site_description: 'Main documentation for enphase'
repo_url: https://github.com/jaysuzi5/enphase
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'